pm2 stop blockchainbox-core
pm2 stop blockchainbox-core-contract-consumer
pm2 stop blockchainbox-core-transaction-consumer
pm2 stop blockchainbox-core-transaction-receipt-consumer
pm2 stop blockchainbox-core-event-consumer
pm2 stop blockchainbox-core-webhook-consumer
pm2 delete blockchainbox-core
pm2 delete blockchainbox-core-contract-consumer
pm2 delete blockchainbox-core-transaction-consumer
pm2 delete blockchainbox-core-transaction-receipt-consumer
pm2 delete blockchainbox-core-event-consumer
pm2 delete blockchainbox-core-webhook-consumer