swagger: '2.0'
info:
  title: Blockchainbox API
  description: Blockchain as a Service, API documents
  version: "1.0.0"
# the domain of the service
host: localhost:3000
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /contract/v1/info:
    get:
      summary: Contract Info
      description: |
        Get contract info by contractId
      parameters:
        - name: contractId
          in: query
          description: Load by contractId.
          required: true
          type: number
          format: double
      tags:
        - Contract
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /contract/v1/event:
    get:
      summary: Contract Event Info
      description: |
        Get contract event info by contract event id
      parameters:
        - name: contractEventId
          in: query
          description: Load by contractEventId.
          required: true
          type: number
          format: double
      tags:
        - Contract
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /event/v1/data:
    get:
      summary: Event data
      description: |
        Get contract event data
      parameters: 
        - name: txHash
          in: query
          description: test
          required: true
          type: string
      tags:
        - Event
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /transaction/v1/data:
    post:
      summary: transaction data
      description: |
        Send transaction data
      parameters: 
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TransactionData'
      tags:
        - Transaction
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
    get:
      summary: transaction data
      description: | 
        Get transaction data
      parameters: 
        - name: txHash
          in: query
          description: txHash
          required: true
          type: string
      tags:
        - Transaction
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /ethereum/v1/compilers:
    get:
      summary: Ethereum compilers
      description: |
        Get Ethereum compilers
      tags:
        - Ethereum
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /ethereum/v1/contract:
    post:
      summary: Deploy contract
      description: |
        Deploy contract to Ethereum
      tags: 
        - Ethereum
      parameters: 
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/SourceCode'
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /ethereum/v1/coinbase:
    get:
      summary: Ethereum coinbase
      description: |
        Get Ethereum coinbase
      tags:
        - Ethereum
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /ethereum/v1/balance:
    get:
      summary: Ethereum account balance
      description: |
        Get Ethereum account balance
      tags:
        - Ethereum
      parameters: 
        - name: address
          in: query
          description: address
          required: false
          type: string
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /ethereum/v1/transactionReceipt:
    get:
      summary: Ethereum transaction receipt
      description: |
        Get Ethereum transaction receipt
      tags:
        - Ethereum
      parameters: 
        - name: transactionHash
          in: query
          description: transactionHash
          required: true
          type: string
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /ethereum/v1/estimateGas:
    get:
      summary: Ethereum estimate gas
      description: |
        Get Ethereum estimate gas
      tags:
        - Ethereum
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /ethereum/v1/gasPrice:
    get:
      summary: Ethereum gas price
      description: |
        Get Ethereum gas price
      tags:
        - Ethereum
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /ethereum/v1/blockNumber:
    get:
      summary: Ethereum block number
      description: |
        Get Ethereum block number
      tags:
        - Ethereum
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /ethereum/v1/hashrate:
    get:
      summary: Ethereum hashrate
      description: |
        Get Ethereum hashrate
      tags:
        - Ethereum
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /ethereum/v1/blockInfo:
    get:
      summary: Ethereum block info
      description: |
        Get Ethereum block info
      tags:
        - Ethereum
      parameters: 
        - name: block
          in: query
          description: block number or block hash
          required: true
          type: string
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
  /ethereum/v1/blockTransactionCount:
    get:
      summary: Ethereum block transaction count
      description: |
        Get Ethereum block transaction count
      tags:
        - Ethereum
      parameters: 
        - name: block
          in: query
          description: block number or string
          required: true
          type: string
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
definitions:
  Contract:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
  TransactionData:
    type: object
    properties:
      contractId:
        type: integer
        format: int32
      contractFunctionId:
        type: integer
        format: int32
      data:
        type: string
  Compiler:
    type: object
    properties:
      compiler:
        type: string
  SourceCode:
    type: object
    properties:
      sourceCode:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
